#!/usr/bin/lua
local site = require 'gluon.site'
local util = require 'gluon.util'
local uci = require('simple-uci').cursor()
local iputil = require 'gluon.iputil'
local sysconfig = require 'gluon.sysconfig'

uci:delete('wireguard', 'mesh_vpn', 'user')

local add_groups

local function generate_section_name(peer)
  return "mesh_vpn_wg_" .. peer
end

local function generate_wg_iface_name(peer)
  return "mesh-vpn-" .. peer
end

local function add_peer(group, name, config, count)
  local ip = iputil.mac_to_ip("fe80::/64", sysconfig.primary_mac)

  uci:section('network', 'interface', generate_section_name(name) .. 'm', {
    type = 'wireguard',
    ifname = generate_wg_iface_name(count),
    proto = 'gluon_mesh',
  })

  uci:section('network', 'interface', generate_section_name(name) .. 's', {
    ip6addr = ip,
    ifname = generate_wg_iface_name(count),
    proto = 'static',
  })

  uci:section('network', 'interface', generate_section_name(name) .. 'w', {
    ifname = generate_wg_iface_name(count),
    proto = 'gluon_wireguard',
  })

  uci:section('wireguard', 'peer', group .. '_peer_' .. name, {
    enabled = true,
    net = 'mesh_vpn',
    ifname = generate_wg_iface_name(count),
    group = group,
    key = config.key,
    remote = config.remote,
    broker_port = config.broker_port,
    allowedIPs = '::/0',
  })
end

local function add_group(name, config, parent)
  uci:delete('wireguard', name)
  uci:delete_all('wireguard', 'peer', function(peer)
    return (peer.net == 'mesh_vpn' and peer.group == name)
  end)


  uci:section('wireguard', 'peer_group', name, {
    enabled = true,
    net = 'mesh_vpn',
    parent = parent,
    peer_limit = config.limit,
  })

  local count=0
  if config.peers then
    for peername, peerconfig in pairs(config.peers) do
      add_peer(name, peername, peerconfig, count)
      count = count + 1
    end
  end

  add_groups(name, config.groups, name)
end

-- declared local above
function add_groups(prefix, groups, parent)
  if groups then
    for name, group in pairs(groups) do
      add_group(prefix .. '_' .. name, group, parent)
    end
  end
end

add_groups('mesh_vpn', site.mesh_vpn.wireguard.groups())

if site.mesh_vpn.wireguard.groups.backbone.enabled(true) then
uci:section('wireguard', 'wireguard', 'mesh_vpn', {
	enabled = true,
	group = 'mesh_vpn_backbone',
	mtu = site.mesh_vpn.mtu(),
	secret = '/lib/gluon/mesh-vpn/wireguard',
	packet_mark = 1,
})
end

uci:save('network')
uci:save('wireguard')
